---
# tasks file for dce_role_project_env
- name: Determine if the project-specific vars file exists
  local_action:
    module: stat
    path: "{{ project_env_path }}"
  register: project_vars_file

- name: Set-up project-specific environment variables
  include_vars: "{{ project_env_path }}" 
  when: project_vars_file.stat.exists
  no_log: True
